POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbXBvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2OTQ1OTY5MTd9.zn9Q03VRjB9XPErdtbv6COKT1nIp9KFiFQhYdW6gT-Q

{
    "author": "Mazai",
    "url": "kokkers",
    "title": "Slavan eurolavat",
    "likes": 0,
    "year": 2004
}