POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvayIsImlkIjoyLCJpYXQiOjE2OTIxNzEyNTN9.ID4wP1qxbkZtCAnpNfsrGc2U2LzuHfHOSVh6sVZKvQ4

{
    "author": "juho",
    "url": "yandex.ru",
    "title": "Juhon juopottelut"
}