PUT http://localhost:3001/api/blogs/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bXBvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2OTUzNzYxNTJ9.NRuzqNe6f2_XNXREEJ9YgnpTsLzp_33X2Mc28d-DHSk

{
    "likes": 2
}